### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by kporras07**
Add What's in the Box, Folder Structure and Credtis.

@Erian7, @fedfigca, @betovarg I accept comments here :D

### CODE REVIEW

**Comment by betovarg** [comment]
Awesone readme.md in my opinion. I would like to hear the technical review from @fedfigca and @Erian7, to know if there is information that might be needed to complement this readme. 

If everything is cool, then we can merge it :)

Thank you so much @kporras07!

**Comment by betovarg** [comment]
Can we merge and close?

**Comment by EdgarBarrantes** [comment]
I'd say merge and close, saw no typos and is clear enough for it's use. 
@fedfigca suggested on chat a Usage section, showing a few examples of how to use it. I'd say a user would welcome it, but the Installation part is more than enough for the user to start, well, using it.

**Comment by fedfigca** [comment]
I already gave my recommendations to Kev and he implemented them, everything else looks great

**Comment by kporras07** [comment]
Thanks to all; merging.

**Pull request merged**
